;   keyhistory working code
SetTitleMatchMode 2
#SingleInstance Force
#Requires Autohotkey v2.0
;
;   this script has to be running already to work
;   (or add this to one you use all the time)
;
;   If the script does not have the keyboard hook installed, the KeyHistory window will 
;   display only the keyboard events generated by the script itself (i.e. not the user's). 
InstallKeybdHook
;
^y:: ; Ctrl y to activate
{
    KeyHistory
    ; Ctrl k is for key history
    ; Ctrl l is lines mose recently executed
    ; Ctrl v is for variables and their contents
    ; Ctrl h is for hotstrings and their methods
}
